// <auto-generated/>
using System.Reflection;

[assembly: AssemblyTitleAttribute("NDceRpc.ServiceModel")]
[assembly: AssemblyProductAttribute("NDceRpc.ServiceModel")]
[assembly: AssemblyDescriptionAttribute("Contains ServiceModel like attributes, errors and interfaces")]
[assembly: AssemblyVersionAttribute("0.2.0.0")]
[assembly: AssemblyFileVersionAttribute("0.2.0.0")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const string Version = "0.2.0.0";
    }
}
