//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: Messages.proto
namespace NDceRpc.ServiceModel.Protobuf
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"FaultData")]
  public partial class FaultData : global::ProtoBuf.IExtensible
  {
    public FaultData() {}
    
    private string _Code;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"Code", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string Code
    {
      get { return _Code; }
      set { _Code = value; }
    }
    private string _Name;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"Name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string Name
    {
      get { return _Name; }
      set { _Name = value; }
    }
    private string _Reason;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"Reason", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string Reason
    {
      get { return _Reason; }
      set { _Reason = value; }
    }

    private string _Detail = "";
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"Detail", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string Detail
    {
      get { return _Detail; }
      set { _Detail = value; }
    }

    private string _Node = "";
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"Node", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string Node
    {
      get { return _Node; }
      set { _Node = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Message")]
  public partial class Message : global::ProtoBuf.IExtensible
  {
    public Message() {}
    
    private byte[] _Data;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"Data", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public byte[] Data
    {
      get { return _Data; }
      set { _Data = value; }
    }

    private FaultData _Fault = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"Fault", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public FaultData Fault
    {
      get { return _Fault; }
      set { _Fault = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RpcParamData")]
  public partial class RpcParamData : global::ProtoBuf.IExtensible
  {
    public RpcParamData() {}
    
    private int _Identifier;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"Identifier", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int Identifier
    {
      get { return _Identifier; }
      set { _Identifier = value; }
    }
    private byte[] _Data;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"Data", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public byte[] Data
    {
      get { return _Data; }
      set { _Data = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MessageRequest")]
  public partial class MessageRequest : global::ProtoBuf.IExtensible
  {
    public MessageRequest() {}
    
    private int _Operation;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"Operation", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int Operation
    {
      get { return _Operation; }
      set { _Operation = value; }
    }
    private readonly global::System.Collections.Generic.List<RpcParamData> _Data = new global::System.Collections.Generic.List<RpcParamData>();
    [global::ProtoBuf.ProtoMember(2, Name=@"Data", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<RpcParamData> Data
    {
      get { return _Data; }
    }
  

    private string _Session = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"Session", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string Session
    {
      get { return _Session; }
      set { _Session = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}
