// <auto-generated/>
using System.Reflection;

[assembly: AssemblyTitleAttribute("NDceRpc.ServiceModel.Core")]
[assembly: AssemblyProductAttribute("NDceRpc.ServiceModel.Core")]
[assembly: AssemblyDescriptionAttribute("RPC based on .NET, MS-RPC, binary serialization and WCF")]
[assembly: AssemblyVersionAttribute("0.2.0.0")]
[assembly: AssemblyFileVersionAttribute("0.2.0.0")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const string Version = "0.2.0.0";
    }
}
